### ISSUE TITLE
5.30 지금 당장 할 수 있는 것을 하기

### ISSUE THREAD

**Issue by JaeyeongYoo** [17-1-SKKU-OSS/021B#4]
프로그램이 안 돌아가서 원이가 pull request를 보냈고, 
wiki랑 issue를 업데이트 했다.
프로젝트에서 제공하는 한글 사전 업데이트에 단어를 올렸다.

ex) 가라사니

그 외의 없는 단어들을 찾아 제공할 예정.

**Comment by Chowonyi** [comment]
이건 wiki로 옮겨야할 내용임
wiki에 내용 합치고 닫음
