### ISSUE TITLE
지킬테마

### ISSUE THREAD

**Issue by JaeyeongYoo** [17-1-SKKU-OSS/021B#5]
구글링하면서 찾아보다가 설명은 친절한데 못알아보겠어서 1차 포기

**Comment by JaeyeongYoo** [comment]
그나마 알아들을법한 유투브 발견해서 테마 zip파일 다운 받고 푼 다음에 집어 넣어봤는데
테마 죄다깨짐 하하핳ㅎ하하

**Comment by Chowonyi** [comment]
Linux 환경에서 내가 해봄 주말에 깔라고 하니까 Linux버전 설명 밖에 없어서 때려쳤었음

**Comment by Chowonyi** [comment]
이거 너무 어려움.... 도움을 구해야 될 듯

**Comment by Chowonyi** [comment]
서연언니(011A, 우리 그룹)가 도와줘서 Theme 적용 완료. 서연언니 짱짱.

**Comment by Chowonyi** [comment]
근데 원래있던 README 없어짐. 다시 써야함.

README 내가 다시 쓸게
Static Page 관리는 재영이가 해줘

**Comment by Chowonyi** [comment]
README 다 바꿈

**Comment by JaeyeongYoo** [comment]
나도 정적페이지 정리 거의 다 했어!!!! 고양이 사진 졸귀탱 ㅎㅎ

**Comment by Chowonyi** [comment]
문제 해결된거지? issue 닫을게

**Comment by Chowonyi** [comment]
(재영이랑 원이가 각자 해보다가 안돼서 서연언니를 불러서 같이 앉아서 하고 나중에 정리한거라 시간 차이가 얼마 없게 나옵니다.)
